// <auto-generated />
using System;
using HomeWorks.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeWorks.Migrations
{
    [DbContext(typeof(MyAppDbContext))]
    [Migration("20240321164213_People")]
    partial class People
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeWorks.Models.Passport", b =>
                {
                    b.Property<int>("PassportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassportId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PassportId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Passport");

                    b.HasData(
                        new
                        {
                            PassportId = 1,
                            BirthDate = new DateTime(1980, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Test1",
                            LastName = "Test1",
                            PersonId = 1,
                            Series = "AC23214"
                        },
                        new
                        {
                            PassportId = 2,
                            BirthDate = new DateTime(1990, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Test2",
                            LastName = "Test2",
                            PersonId = 2,
                            Series = "AD234234"
                        },
                        new
                        {
                            PassportId = 3,
                            BirthDate = new DateTime(2001, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Test3",
                            LastName = "Test3",
                            PersonId = 3,
                            Series = "SA2423424"
                        },
                        new
                        {
                            PassportId = 4,
                            BirthDate = new DateTime(2005, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Test4",
                            LastName = "Test4",
                            PersonId = 4,
                            Series = "AD837874"
                        });
                });

            modelBuilder.Entity("HomeWorks.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Age = 44,
                            Name = "Test1"
                        },
                        new
                        {
                            PersonId = 2,
                            Age = 34,
                            Name = "Test"
                        },
                        new
                        {
                            PersonId = 3,
                            Age = 23,
                            Name = "Test"
                        },
                        new
                        {
                            PersonId = 4,
                            Age = 19,
                            Name = "Test"
                        });
                });

            modelBuilder.Entity("HomeWorks.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirtDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Address = "Test1",
                            BirtDate = new DateTime(2024, 3, 21, 21, 42, 12, 776, DateTimeKind.Local).AddTicks(8220),
                            City = "Test1",
                            Cours = "Test1",
                            FirstName = "Test1",
                            LastName = "Test1"
                        },
                        new
                        {
                            StudentId = 2,
                            Address = "Test2",
                            BirtDate = new DateTime(2024, 3, 20, 21, 42, 12, 776, DateTimeKind.Local).AddTicks(8234),
                            City = "Test2",
                            Cours = "Test2",
                            FirstName = "Test2",
                            LastName = "Test2"
                        },
                        new
                        {
                            StudentId = 3,
                            Address = "Test3",
                            BirtDate = new DateTime(2024, 2, 21, 21, 42, 12, 776, DateTimeKind.Local).AddTicks(8249),
                            City = "Test3",
                            Cours = "Test3",
                            FirstName = "Test3",
                            LastName = "Test3"
                        },
                        new
                        {
                            StudentId = 4,
                            Address = "Test4",
                            BirtDate = new DateTime(2024, 1, 21, 21, 42, 12, 776, DateTimeKind.Local).AddTicks(8257),
                            City = "Test4",
                            Cours = "Test4",
                            FirstName = "Test4",
                            LastName = "Test4"
                        });
                });

            modelBuilder.Entity("HomeWorks.Models.Passport", b =>
                {
                    b.HasOne("HomeWorks.Models.Person", "Person")
                        .WithOne("Passport")
                        .HasForeignKey("HomeWorks.Models.Passport", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HomeWorks.Models.Person", b =>
                {
                    b.Navigation("Passport")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
