// <auto-generated />
using System;
using HomeWorks.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeWorks.Migrations
{
    [DbContext(typeof(MyAppDbContext))]
    [Migration("20240321162221_Students")]
    partial class Students
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeWorks.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirtDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Address = "Test1",
                            BirtDate = new DateTime(2024, 3, 21, 21, 22, 21, 464, DateTimeKind.Local).AddTicks(9864),
                            City = "Test1",
                            Cours = "Test1",
                            FirstName = "Test1",
                            LastName = "Test1"
                        },
                        new
                        {
                            StudentId = 2,
                            Address = "Test2",
                            BirtDate = new DateTime(2024, 3, 20, 21, 22, 21, 464, DateTimeKind.Local).AddTicks(9938),
                            City = "Test2",
                            Cours = "Test2",
                            FirstName = "Test2",
                            LastName = "Test2"
                        },
                        new
                        {
                            StudentId = 3,
                            Address = "Test3",
                            BirtDate = new DateTime(2024, 2, 21, 21, 22, 21, 464, DateTimeKind.Local).AddTicks(9955),
                            City = "Test3",
                            Cours = "Test3",
                            FirstName = "Test3",
                            LastName = "Test3"
                        },
                        new
                        {
                            StudentId = 4,
                            Address = "Test4",
                            BirtDate = new DateTime(2024, 1, 21, 21, 22, 21, 464, DateTimeKind.Local).AddTicks(9960),
                            City = "Test4",
                            Cours = "Test4",
                            FirstName = "Test4",
                            LastName = "Test4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
